services:
  web:
    build: .
    image: "lemanouthe/generator"
    container_name: generator
    command: ["sh", "./start.sh"]
    ports:
      - "8006:8006"
    volumes:
      - .:/web
      - staticfiles:/web/staticfiles
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"  # Permet d'exposer PostgreSQL pour le réseau interne Docker
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=generator
      - POSTGRES_USER=generator
      - POSTGRES_PASSWORD=generator-db-pwd


volumes:
    postgres_data:
    staticfiles: